' Developer Express Code Central Example:
' How to change the appearance of a focused data row and selected rows
' 
' This example demonstrates how to use the View's RowStyle property to apply
' custom styles to focused and selected rows. To identify whether a row is focused
' and selected, the attached IsFocusedRow and IsSelected properties are used.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E2066
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace DXGrid_ChangeRowAppearance.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As DXGrid_ChangeRowAppearance.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New DXGrid_ChangeRowAppearance.Properties.Settings())), DXGrid_ChangeRowAppearance.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return DXGrid_ChangeRowAppearance.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
